name: test_remote_api
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: All remote tests
      env:
        DOCKER_LOGIN_TOKEN: ${{ secrets.DOCKER_LOGIN_TOKEN }}
        NHLAPI_REMOTE_TESTS: true
      run: sh ci/docker_stage.sh ci/test_all.R
